---
title: "Ass_2"
author: "Christoffersen J. & Haugland V."
date: "Oktober 14. 2021"
output:
  pdf_document: default
  html_notebook: default
---

# Del 1 - Innledning

Bare en liten test.

## Kort innledning

Det eksisterer en mengde ulike faktorer som vil være med på å bestemme et individs inntekt. For eksempel, i tilskrivnings-kulturer som Japan er status noe som blir tildelt for hvem eller hva en person er, framfor hvordan de utfører sine oppgaver. Dette er et nokså bredt eksempel på tvers av kulturer, men forskning har vist at det er en rekke biologiske faktorer som bestemmer hvordan vi mennesker tildeler status og annerkjennelse, ergo. hvor mye individer kan forvente å tjene. Disse faktorene vil ikke være absolutt avgjørende, men de har tendenser og er blant annet at blondiner tjener mer enn brunetter, skallete menn tjener mindre enn menn med fullt hår og at høye individer tjener mer enn lave individer. Det sistnevnde gjelder spesielt for menn og faktoren angående høyde kommer være problemstillingen vår for dette mini-paperet som er *Er det høyde som bestemmer inntekt?*. For å belyse denne problemstillingen skal vi benytte oss av datasettet *heights* fra R-pakken *modlr*, og gjennomføre en rekke ulike regresjonsanalyser med henhold til hvordan *høyde* og en rekke andre variabler påvirker inntekten. Resultatene fra disse analysene sklal videre benyttes til lineære hypotesetester, hvor vi skal undersøke og konkludere variablen *høyde* sin effekt på inntekt. 

## Kort litteraturgjennomgang på ca. 1 side

For å anskaffe en bredere forståelse av dette fenomenet med høyde sin påvirkning på individets inntekt, skal vi kort gjennomgå artikkelen *The Effect of Physical Hieght on Workplace Sucess and Income: Prelimitary Test of a Theoretical Model*. Her undersøkte de forholdet mellom høyde og hvilken type karrieresuksess individene hadde. Resultatene fremviste at fysisk høyde har en signifikant påvirkning på individets sosiale aktelse, ledelse fremheving og ytelse **(Judge et al., 2004)** 

Det eksisterer mange underliggende faktorerer som er med på å påvirke hvorfor høyde er så ønskelig. For det første er høye individer ansett som potensielt mer suksessfulle enn de som er lavere. En grunn til dette er at høyde er en sosialt ønskelig ressurs med mange goder. For eksempel, vil de som er høye bli betraktet som mer overbevisende, mer attraktiv som partner og ha en større sannsynlighet for å bli en fremtidig leder. For å illustrere sistnevnte, så kan vi se at det ikke har blitt utvalgt en president i USA som er lavere enn den gjennomsnittlige høyden helt siden 1896 **(Judge et al., 2004)**. Høydens viktighet er ikke bare observert blant mennesker, men vi ser den også i dyreriket. For dyrene er høyde noe som er svært enkelt å observere og dermed blir brukt som en indeks for dens makt og styrke, noe som spesielt fremvises i livstruende situasjoner. Vi kan dermed si fra et slikt sosiobiologisk perspektiv, at høyde vil tilegne seg makt og makt er noe som videre fører til respekt. I jobbsammenhenger kan høydens viktighet bli fremvist tydligere, med henhold til at dette er en arena hvor faktorer som overtalelse og makt er ansett som uhyrlig viktige. Det er gjennomført flere ulike undersøkelser på høyde innen jobbsammenhenger og de viser blant annet betyningen når det kommer til hvordan høye salgspersoner blir betraktet i større grad og at lave politibetjenter kan forvente en større grad av klager enn høye politbetjenter **(Judge et al., 2004)**.

For å forstå disse underliggende faktorene til høyde kan vi benytte den teoretiske modellen for forholdet mellom høyde og karriere til å forklare dette sosiale fenomenet. For det første vil høyde ha en stor betydning for hvordan vi betrakter oss selv, altså vår selvtillit og selvfølelse. Med henhold til at høyde er sterkt korrelert med sosial makt, vil lave individer stå i fare for å være misfornøyde med sin fysiske form, og denne usikkerheten vil være med på å påvirke personligheten deres. Et ekstremt eksempel på dette vil være det som kalles *Napoleon kompleks*, hvor individets høyde har så stor negativ betydning som fører til at denne mangelen på høyde fører til at man føler seg utilstrekkelig som individ, som resulterer i en svært aggresiv opptreden **(Just et al., 2003)**

Høyde vil i likhet med selvtillitten påvirke hvordan individet vil bli betraktet av andre, altså den sosiale aktelsen. For eksempel, vil dette i stor grad føre til høyere objektiv ytelse, som er jobb eller oppgave utfall og resultater. Noe som kan spesielt observeres i situasjoner hvor sosiale interaksjoner er ansett som viktige. Dette kan fremvises ved at kunder tenderer til å gi mer betraktning mot høye individer, som gjør at de i større grad kommer kjøpe av en høy salgsperson. Denne berudringen vil også være essensiell i andre sammenehenger, slikt som å opprette tillit, motta informasjon og mer effektiv forhandling **(Judge et al., 2004)**, som vil resultere i økt effektivitet og ytelse. Individets egne selvtilitt vil også ha en stor påvirkning på ytelsen. En positiv selvtillitt er nært knyttet til høyere ytelse ved at slike individer gjerne blir ansett som mer gunstige og er dermed lettere likt blant andre. 

Det siste steget i modellen forklarer hvordan denne ytelsen vil ha en påvirkning på videre suksess i karrieren. Med den økte sosiale aktelsen og selvtilittien det høye individet innehar, vil resultere i høyere ytelse. Denne ytelsen gjennom mer effektiv produktiviet vil dermed føre til organisatoriske belønninger som blant annet høyere lønninger og forfremmelser.

- Judge, T. A., & Cable, D. M. (2004). The effect of physical height on workplace success and income: preliminary test of a theoretical model. Journal of Applied Psychology, 89(3), 428.

- Just, W., & Morris, M. R. (2003). The Napoleon complex: why smaller males pick fights. Evolutionary Ecology, 17(5), 509-522.




